# Generated by Django 5.0.3 on 2024-04-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_producto_imagen_producto_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(default='https://www.libreriahuequito.com/public/images/productos/default.png'),
        ),
    ]
